apiVersion: v1
kind: Service
metadata:
  name: kubefoods-service
spec:
  type: NodePort
  selector:
    app: kubefoods
  ports:
    - port: 80
      targetPort: 81 # esto deberia ser 80, lo cambiamos para forzar el error
      nodePort: 30080